// const GET_DATA = 'ROUTES_GET_DATA'
// const SET_DATA = 'ROUTES_SET_DATA'
// const SET_DATA = 'ROUTES_SET_DATA'
//
// export default {
//   GET_DATA,
//   SET_DATA,
// }

const ADD_STATION = 'ROUTES_ADD_STATION'
const REMOVE_STATION = 'ROUTES_REMOVE_STATION'
const REMOVE_LAST_STATION = 'ROUTES_REMOVE_LAST_STATION'

export default {
  ADD_STATION,
  REMOVE_STATION,
  REMOVE_LAST_STATION,
}
